services:
  jenkins-docker:
    build: .
    user: root
    privileged: true
    environment:
      DOCKER_HOST: unix:///var/run/docker.sock
    volumes:
      - jenkins-data:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - '8082:8080'
      - '50000:50000'
    networks:
      - jenkins

volumes:
  jenkins-data:

networks:
  jenkins:
